### PR TITLE
Prevent AddWatchedAddress from adding a script that represents an exi…

### PR DESCRIPTION
**Pull request by rodkeys**
These changes ensure that AddWatchedAddress should never add a script which already represents a key from the appropriate wallet.

Also added tests to verify that watch scripts are added properly. Finishes issue #107.

### CODE REVIEW

**Comment by hoffmabc** [comment]
We're migrating to AddWatchedAddresses from AddWatchedAddress so this will probably need to be refactored.

**Comment by hoffmabc** [comment]
See: https://github.com/OpenBazaar/multiwallet/pull/108

**Comment by rodkeys** [comment]
> We're migrating to AddWatchedAddresses from AddWatchedAddress so this will probably need to be refactored.

Alright thanks for the heads up, I'll wait for that PR to get merged and then refactor

**Comment by placer14** [comment]
@rodkeys The dependant PR is merged. LMK after you've updated and this is ready to review.

**Pull request merged**
