### PR TITLE
Remove logging for port parsing

### PR DESCRIPTION
**Pull request by placer14**

### CODE REVIEW

**Comment by tyler-smith** [comment]
I'm not sure why the tests are failing.

I'd change the commit message to reflect what the change is now doing.

**Comment by cpacia** [comment]
Not sure an error log is appropriate here given that it's expect to print that error in the normal case where a url is passed in with a port.

**Comment by placer14** [comment]
Removed the log and simplified the check to assign the port only when not erroring.

**Comment by cpacia** [comment]
Implemented in the cacher PR

**Pull request closed without merging**
